# Generated by Django 4.2.5 on 2023-09-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putyouon', '0005_rename_song_review_song_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='song_id',
            new_name='song',
        ),
    ]
